AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Lambda
Resources:
  CloudTrailMultiAccountPolicyGenerator:
    Type: AWS::Serverless::Function
    Properties:
      # as soon as we rely on third-party depedencies (pip packages to `virtualenv`), we are
      # forced to create a zip-file, containing all relevant data
      CodeUri: bundle.zip
      Handler: generator.generatebucketpolicy.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          BUCKET_NAME: your_bucket_name_here
          CLOUDTRAIL_LOG_PREFIX: your_log_prefix_here
          ACCOUNTS_PER_BUCKET: '100'
